# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hang
tagline:          'BLOGS'
description:      CS@JACOBS Uni 2017
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Hang Yuan'
  url:            https://de.linkedin.com/pub/hang-calvin-yuan/56/464/ba4

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/angerhang
