# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hyde
tagline:          'BLOGS'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Hang Yuan'
  url:            https://de.linkedin.com/pub/hang-calvin-yuan/56/464/ba4

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/angerhang
